language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

sudo: false

matrix:
    include:
        - php: 5.5.9
          env: setup=lowest
        - php: 5.5.9
          env: setup=stable
        - php: 7.0
          env: setup=stable
    allow_failures:
        - php: 5.5
        - php: 7.0
        - php: 7.1
    fast_finish: true

script:
  - phpunit --configuration phpunit.xml --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --access-token="53c569dececa0578c84587178c5f08e25df8c6e42c37bd313bf0802d2cf74a71" --format=php-clover coverage.clover

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/cf4cb46c56710f9fc4f8
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
  email:
    - gjero@krsteski.de

